server:
  port: 8081

spring:
  application:
    name: NOTIFICATION-SERVICE
  mail:
    host: smtp.gmail.com
    port: 587
    username: elmurodov1106@gmail.com
    password: rehixeessiscctor
    properties:
      mjaail:
        smtp:
          auth: true
      mail:
        smtp:
          starttls:
            enable: true



eureka:
  client:
    service-url:
      defaultUrl: ${EUREKA_URI:http://165.232.104.233/8761:8761/eureka/}
    instance:
      preferIpAddress: true

